[package]
name = "hyper-proxy"
version = "0.4.1"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
description = "A proxy connector for Hyper-based applications"

documentation = "https://docs.rs/hyper-proxy"
repository = "https://github.com/tafia/hyper-proxy"

readme = "README.md"
keywords = ["hyper", "proxy", "tokio", "ssl"]
categories = ["web-programming::http-client", "asynchronous", "authentication"]
license = "MIT"

[dependencies]
http = "0.1"
hyper = "0.12"
futures = "0.1.17"
tokio-io = "0.1.6"
bytes = "0.4.6"
tokio-tls = { version = "0.2", optional=true }
hyper-tls = { version = "0.3", optional=true }
native-tls = { version = "0.2", optional=true }

[dev-dependencies]
tokio = "0.1"
tokio-tcp = "0.1"

[features]
tls = ["tokio-tls", "hyper-tls", "native-tls"]
default = ["tls"]
